//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumpstartMenu.Adapters
{
    
    public class IMessageContractViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IMessageContractContract
    {
        private JumpstartMenu.Views.IMessageContract _view;
        public IMessageContractViewToContractAddInAdapter(JumpstartMenu.Views.IMessageContract view)
        {
            _view = view;
        }
        public System.AddIn.Contract.IListContract<Start9.Api.Contracts.IMessageEntryContract> Entries
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<JumpstartMenu.Views.IMessageEntry, Start9.Api.Contracts.IMessageEntryContract>(_view.Entries, JumpstartMenu.Adapters.IMessageEntryAddInAdapter.ViewToContractAdapter, JumpstartMenu.Adapters.IMessageEntryAddInAdapter.ContractToViewAdapter);
            }
        }
        internal JumpstartMenu.Views.IMessageContract GetSourceView()
        {
            return _view;
        }
    }
}

